export const icebreakerQuestions = [
    "Netflix binge or outdoor adventure date? 🍿🏞️",
    "Big spoon or little spoon? 🥄💕",
    "Coffee date or sunset walk? ☕🌅",
    "Morning person or night owl? 🌅🌙",
    "What's your love language? 💌",
    "First date: fancy dinner or food truck adventure? 🍽️🚚",
    "Beach vacation or mountain getaway? 🏖️⛰️",
    "What song makes you think of romance? 🎵💘",
    "Cooking together or ordering takeout? 👨‍🍳📦",
    "What's your biggest turn-on in a conversation? 😍✨",
    "Text flirting or voice note flirting? 📱🎤",
    "What's your go-to move to impress someone? 😏💫",
    "Rooftop dinner or cozy living room date? 🏙️🛋️",
    "Ever had a meet-cute moment in real life? 🙊💕",
    "Who makes the first move: you or them? 👑",
    "Your place or a surprise location? 🏡✨",
    "Cuddle and talk or cuddle and watch a movie? 🤗🎬",
    "What's your dream date scenario? 💭💕",
    "Matching Halloween costumes: cute or cringe? 🎃👻",
    "What's your relationship dealbreaker? 🚫",
    "Surprise flowers or planned romantic gesture? 💐🎁",
    "One amazing date or steady dating? 💯",
    "What makes you instantly attracted to someone? 🔥😊",
    "Favorite feature you notice first? 👀✨",
    "Love notes: adorable or old-fashioned? 💋📝",
    "How soon is too soon to say 'I like you'? ⏰💕",
    "What's your ideal number of dates before getting serious? 🔢",
    "Do you laugh loud when something's funny? 🔊😄",
    "Morning coffee kiss or goodnight text? 😘☕",
    "Second date immediately or wait a few days? 📅💭",
    "Keep it casual or catch feelings? ❤️🎭",
    "Your biggest dating regret? 🤔",
    "Traditional romance or spontaneous adventure? 🍦🎢",
    "What's your post-date ritual? 🛁📱",
    "When was your first crush? 🌟💕",
    "What's your love style: words, touch, or gifts? ⛓️💝",
    "Ever written someone a love letter? 🖤✍️",
    "Hold hands on the first date or wait? 🤝💕",
    "Long hugs or quick pecks? 😮‍💨💋",
    "What's your wildest date idea? 🤫🎢",
    "Would you ever do a couple's challenge? 👥📹",
    "What scenario would you roleplay on a date? (Strangers meeting, time travelers?) 🎬",
    "Shopping for matching outfits: fun or too much? 🛍️👔",
    "Building IKEA furniture together: relationship test? 🎮🛠️",
    "If things get awkward, what's your go-to joke? 🚦😂",
    "Beach sunset or stargazing? 🏖️⭐",
    "Ever thought about an ex while on a date? 😬",
    "Dating someone new or reconnecting with a past crush? 👤💭",
    "Taking mirror selfies together: cute or narcissistic? 🪞📸",
    "What's your guilty pleasure movie for date night? 📹🍿",
    "Ever had a date on a plane? ✈️💕",
    "Drive-in movie or fancy cinema? 🚗🎥",
    "Would you sing karaoke in front of your date? 👁️🎤",
    "Cooking a meal together: fun or stressful? 🍓👨‍🍳",
    "What's the sweetest dream you've had about someone? 😴💭",
    "Do you like playful teasing or serious conversation? 💉🗣️",
    "Playful competition or teamwork? 👋🏆",
    "Compliments during a date or show through actions? 🗣️💪",
    "Would you let someone plan a surprise date for you? 😶🎁",
    "Hot cocoa by the fire or ice cream in summer? 🧊🔥",
    "What's your opinion on hand-holding in public? 👣🤝",
    "What's something you'd never do on a first date? 🛑",
    "Would you ever do a cheesy pickup line? 🎀😄",
    "Casual streetwear or dressed up fancy? 🖤👗",
    "Have you tried baking cookies together as a date idea? 🍦🍪"
];

export const getRandomQuestion = () => {
    const randomIndex = Math.floor(Math.random() * icebreakerQuestions.length);
    return icebreakerQuestions[randomIndex];
};
